# Generated by Django 5.2.7 on 2025-10-25 11:39

from django.db import migrations

def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')

    for i in ItemModel.objects.all():
        if i.price <= 10:
            i.rarity = 'Rare'
        elif i.quantity <= 20:
            i.rarity = 'Very Rare'
        elif i.quantity <= 30:
            i.rarity = 'Extremely Rare'
        else:
            i.rarity = 'Mega Rare'
        i.save()

def reverse_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    default_rarity = ItemModel._meta.get_field('rarity').default

    for i in ItemModel.objects.all():
        i.rarity = default_rarity
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(
            code=set_rarity,
            reverse_code=reverse_rarity
        )
    ]
