# Generated by Django 5.2.7 on 2025-10-25 16:04

from django.db import migrations

def set_new_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    for s in SmartphoneModel.objects.all():
        s.price = len(s.brand) * 120
        s.save()

def set_new_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    for s in SmartphoneModel.objects.all():
        if s.price <= 750:
            s.category = 'Cheap'
        else:
            s.category = 'Expensive'
        s.save()

def set_new_price_and_category(apps, schema_editor):
    set_new_price(apps, schema_editor)
    set_new_category(apps, schema_editor)

def reverse_set_new_price_and_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_price = SmartphoneModel._meta.get_field('price').default
    default_category = SmartphoneModel._meta.get_field('category').default

    for s in SmartphoneModel.objects.all():
        s.price = default_price
        s.category = default_category
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_new_price_and_category,
            reverse_code=reverse_set_new_price_and_category
        )
    ]
