# Generated by Django 5.2.7 on 2025-10-25 17:04
from datetime import timedelta

from django.db import migrations

from main_app.choices import OrderStatusChoices


def set_fields(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')

    for o in OrderModel.objects.all():
        if o.status == OrderStatusChoices.PENDING:
            o.delivery = o.order_date + timedelta(days=3)
            o.save()
        elif o.status == OrderStatusChoices.COMPLETED:
            o.warranty = "24 months"
            o.save()
        elif o.status == OrderStatusChoices.CANCELLED:
            o.delete()

def reverse_set_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(
            code=set_fields,
            reverse_code=reverse_set_fields
        )
    ]
