# Generated by Django 5.2.7 on 2025-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
